triggers:
   - name: triggerv2sp1per
     type: trigger
     version:
       counter: 944
   - name: triggerv2sp2per
     type: trigger
     version:
       counter: 180
       
   - name: triggerv2sp3per
     type: trigger
     version:
       counter: 166
